# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Cust_Id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Cust_Name', models.CharField(default='NULL', max_length=30)),
                ('Cust_address', models.CharField(default='NULL', max_length=80)),
                ('contact', models.CharField(default='NULL', max_length=15)),
                ('Email_Id', models.CharField(default='NULL', max_length=25)),
                ('Payment_Dues', models.IntegerField(default=0)),
                ('Usual_purchase_details', models.TextField(default='NULL')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
