# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=50)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Rate', models.DecimalField(decimal_places=2, default=12.5, max_digits=7)),
                ('Dues', models.IntegerField(default=0)),
                ('Amount_given', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Total_amt', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('New_Dues', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Payment_Date', models.DateField()),
                ('Payment_details', models.CharField(choices=[('CASH', 'Cash'), ('OTHERS', 'Others')], default='CASH', max_length=6)),
            ],
        ),
    ]
