# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calf',
            fields=[
                ('calf_Id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NULL', max_length=30)),
                ('Breed', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(default=datetime.date.today, null=True)),
                ('age', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='U', max_length=8)),
                ('pno_buyer', models.CharField(default='NULL', max_length=200)),
                ('pno_seller', models.CharField(default='NULL', max_length=200)),
                ('Insurance', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('date_of_expiry_insurance', models.DateField(null=True)),
                ('dehorning', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('One_time_Vaccination', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('Remarks', models.TextField(default='NULL')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
