# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_cattle_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
    ]
