# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0003_cattle_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='Delivery_calf',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Fail', 'Miscarriage')], default='M', max_length=4),
        ),
    ]
