# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0004_cattle_delivery_calf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cattle',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
