# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0006_auto_20160925_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cattle',
            name='id',
        ),
        migrations.AddField(
            model_name='cattle',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cattle',
            name='dehorning',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AddField(
            model_name='cattle',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='pno_buyer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='pno_seller',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='cattle_Id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='heatrecord',
            name='cattle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.Cattle'),
        ),
    ]
