# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0007_auto_20161011_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='Date_BQ',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Date_Brucella',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Date_FMD',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Date_HS',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Date_T',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Deworming_1st_quarter_confirmation',
            field=models.BooleanField(choices=[(1, b'Yes'), (0, b'No')], default=0),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Deworming_1st_quarter_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Deworming_2nd_quarter_confirmation',
            field=models.BooleanField(choices=[(1, b'Yes'), (0, b'No')], default=0),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Deworming_2nd_quarter_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Deworming_3rd_quarter_confirmation',
            field=models.BooleanField(choices=[(1, b'Yes'), (0, b'No')], default=0),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Deworming_3rd_quarter_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Deworming_4th_quarter_confirmation',
            field=models.BooleanField(choices=[(1, b'Yes'), (0, b'No')], default=0),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Deworming_4th_quarter_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Deworming_medicine_name_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Deworming_medicine_name_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Deworming_medicine_name_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Deworming_medicine_name_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Vaccine_BQ_confirmation',
            field=models.BooleanField(choices=[(1, b'Yes'), (0, b'No')], default=0),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Vaccine_FMD_confirmation',
            field=models.BooleanField(choices=[(1, b'Yes'), (0, b'No')], default=0),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Vaccine_HS_confirmation',
            field=models.BooleanField(choices=[(1, b'Yes'), (0, b'No')], default=0),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Vaccine_for_Black_Quarter_BQ',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Vaccine_for_Brucella',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Vaccine_for_Brucella_confirmation',
            field=models.BooleanField(choices=[(1, b'Yes'), (0, b'No')], default=0),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Vaccine_for_Foot_and_Mouth_disease_FMD',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Vaccine_for_Hemorrhagic_Septicemia_HS',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Vaccine_for_Theileriosis',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Vaccine_for_Theileriosis_confirmation',
            field=models.BooleanField(choices=[(1, b'Yes'), (0, b'No')], default=0),
        ),
        migrations.AlterField(
            model_name='heatrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
