# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0008_auto_20161115_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='Deworming_medicine_name_1',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Deworming_medicine_name_2',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Deworming_medicine_name_3',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Deworming_medicine_name_4',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Vaccine_for_Black_Quarter_BQ',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Vaccine_for_Brucella',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Vaccine_for_Foot_and_Mouth_disease_FMD',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Vaccine_for_Hemorrhagic_Septicemia_HS',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Vaccine_for_Theileriosis',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='name',
            field=models.CharField(default=b'NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='pno_buyer',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='pno_seller',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
    ]
