# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0013_auto_20161115_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='New_Dues',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
