# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0014_auto_20161115_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='Confirmation_after_oneMonth',
            field=models.BooleanField(choices=[(1, b'Yes'), (0, b'No')], default=0),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Confirmation_after_threeMonth',
            field=models.BooleanField(choices=[(1, b'Yes'), (0, b'No')], default=0),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Delivery_status',
            field=models.CharField(choices=[(b'safe', b'Safe'), (b'Not Safe', b'Not Safe')], default=b'safe', max_length=4),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Expected_date_of_Delivery',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Insurance',
            field=models.BooleanField(choices=[(1, b'Yes'), (0, b'No')], default=0),
        ),
        migrations.AddField(
            model_name='cattle',
            name='Semen_details',
            field=models.CharField(default=b'NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='cattle',
            name='date_of_expiry_insurance',
            field=models.DateField(null=True),
        ),
    ]
