# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0016_calf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calf',
            name='Remarks',
            field=models.TextField(default=b'NULL'),
        ),
    ]
