# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0018_auto_20161115_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='Breed',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
