# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0020_auto_20161119_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calf',
            name='sex',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'U', max_length=8),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Delivery_calf',
            field=models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female'), (b'Fail', b'Miscarriage')], default=b'Male', max_length=8),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Delivery_status',
            field=models.CharField(choices=[(b'safe', b'Safe'), (b'Not Safe', b'Not Safe')], default=b'safe', max_length=8),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='sex',
            field=models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], default=b'U', max_length=8),
        ),
    ]
