# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0023_auto_20161119_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='Confirmation_after_oneMonth',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=4),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Confirmation_after_threeMonth',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=4),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Deworming_1st_quarter_confirmation',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=4),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Deworming_2nd_quarter_confirmation',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=4),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Deworming_3rd_quarter_confirmation',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=4),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Deworming_4th_quarter_confirmation',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=4),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Insurance',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=4),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Vaccine_BQ_confirmation',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=4),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Vaccine_FMD_confirmation',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=4),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Vaccine_HS_confirmation',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=4),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Vaccine_for_Brucella_confirmation',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=4),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='Vaccine_for_Theileriosis_confirmation',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=4),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='dehorning',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], default=b'No', max_length=4),
        ),
    ]
