# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0024_auto_20161119_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calf',
        ),
    ]
