# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0025_delete_calf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
