# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0026_delete_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('title', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Chat Entry',
                'verbose_name_plural': 'Chat Entries',
            },
        ),
    ]
